/**
 * The model price catalogue, and the loader that brings it into the page.
 *
 * ## Shape of the data
 *
 * `public/data/model-pricing.json` is generated by `scripts/fetch-model-pricing.mjs`
 * from LiteLLM's published price list — around 2,400 token-priced models across
 * 80-odd providers. It is deliberately *not* bundled into the JS: at ~290 kB it
 * would triple the weight of every tool page, including the three that never
 * quote a price. It is fetched on demand from the same origin, once per tab.
 *
 * ## Why there is still a hardcoded table
 *
 * `src/data/models.ts` carries a handful of curated entries. They serve two
 * purposes: they are the default comparison set (a catalogue of 2,400 rows is
 * useless as a starting position), and they are the fallback if the fetch fails.
 * A tool that shows nothing when one asset 404s is worse than one that shows
 * four models and says so.
 *
 * ## Units
 *
 * Every price in this module is **USD per million tokens** — the unit vendors
 * publish. `src/lib/tokens.ts#costOf` expects the same, so the two compose
 * without a conversion step anyone can get wrong.
 */

import { MODELS, effectivePrice, type ModelInfo } from '../data/models';
import { href } from './url';

/** Modes retained by the generator. All are priced per token. */
export type ModelMode = 'chat' | 'completion' | 'responses' | 'embedding';

/** Capability flags, unpacked from the generator's bitfield. */
export interface ModelCapabilities {
  readonly tools: boolean;
  readonly vision: boolean;
  readonly reasoning: boolean;
  readonly caching: boolean;
  readonly schema: boolean;
  readonly pdf: boolean;
  readonly audio: boolean;
  readonly websearch: boolean;
  readonly computer: boolean;
}

export type CapabilityName = keyof ModelCapabilities;

/** One model, normalised for display. */
export interface PricedModel {
  readonly id: string;
  /** Display name — the id for catalogue entries, a friendly name for curated ones. */
  readonly name: string;
  readonly provider: string;
  readonly mode: ModelMode;
  /** Context window in tokens, where the provider publishes one. */
  readonly context?: number;
  readonly maxOutput?: number;
  /** USD per 1M input tokens. */
  readonly input: number;
  /** USD per 1M output tokens. Zero for embedding models. */
  readonly output: number;
  /** USD per 1M cached input tokens read. */
  readonly cacheRead?: number;
  /** USD per 1M tokens written to cache. */
  readonly cacheWrite?: number;
  /** ISO date the provider retires the model, if announced. */
  readonly deprecation?: string;
  readonly caps: ModelCapabilities;
  /** True for the hand-maintained entries — pinned to the top of the list. */
  readonly curated: boolean;
  /** Positioning line, curated entries only. */
  readonly note?: string;
}

export interface PriceCatalogue {
  readonly models: readonly PricedModel[];
  readonly providers: readonly string[];
  /** ISO date the snapshot was taken. */
  readonly fetched: string;
  readonly source: string;
  /** False when the fetch failed and only the curated fallback is present. */
  readonly complete: boolean;
}

/** Raw record as written by `scripts/fetch-model-pricing.mjs`. */
interface RawModel {
  i: string;
  p: string;
  m: string;
  ci?: number;
  co?: number;
  in: number;
  out: number;
  cr?: number;
  cw?: number;
  d?: string;
  f?: number;
}

interface RawCatalogue {
  revision: string | null;
  fetched: string;
  source: string;
  unit: string;
  flags: readonly CapabilityName[];
  providers: readonly string[];
  models: readonly RawModel[];
}

const NO_CAPS: ModelCapabilities = {
  tools: false,
  vision: false,
  reasoning: false,
  caching: false,
  schema: false,
  pdf: false,
  audio: false,
  websearch: false,
  computer: false,
};

/** Unpack the generator's bitfield against the flag order it shipped with. */
function unpackCaps(bits: number | undefined, order: readonly CapabilityName[]): ModelCapabilities {
  if (!bits) return NO_CAPS;
  const caps: Record<string, boolean> = { ...NO_CAPS };
  order.forEach((name, i) => {
    caps[name] = (bits & (1 << i)) !== 0;
  });
  return caps as unknown as ModelCapabilities;
}

const VALID_MODES = new Set<ModelMode>(['chat', 'completion', 'responses', 'embedding']);

function toMode(value: string): ModelMode {
  return VALID_MODES.has(value as ModelMode) ? (value as ModelMode) : 'chat';
}

/**
 * Curated entries as catalogue rows.
 *
 * Promotional pricing is resolved at call time via `effectivePrice`, so a
 * promotion that lapses stops being quoted without an edit here.
 */
function curatedModels(now: Date): PricedModel[] {
  return MODELS.map((model: ModelInfo): PricedModel => {
    const price = effectivePrice(model, now);
    return {
      id: model.id,
      name: model.name,
      provider: 'anthropic',
      mode: 'chat',
      context: model.context,
      input: price.input,
      output: price.output,
      caps: { ...NO_CAPS, tools: true, vision: true, caching: true, schema: true, reasoning: true },
      curated: true,
      note: model.note,
    };
  });
}

/** Ids shown by default, before the visitor picks anything. */
export const DEFAULT_SELECTION: readonly string[] = MODELS.map((m) => m.id);

/** The catalogue with only the curated entries — used when the fetch fails. */
export function fallbackCatalogue(now: Date = new Date()): PriceCatalogue {
  return {
    models: curatedModels(now),
    providers: ['anthropic'],
    fetched: '',
    source: '',
    complete: false,
  };
}

/**
 * One in-flight load per tab.
 *
 * Every consumer awaits the same promise, so a page with two islands that both
 * need prices still makes one request.
 */
let pending: Promise<PriceCatalogue> | null = null;

/**
 * Load the price catalogue.
 *
 * Never rejects: a failed fetch resolves to {@link fallbackCatalogue}, flagged
 * `complete: false` so the UI can say what the visitor is looking at.
 */
export function loadCatalogue(now: Date = new Date()): Promise<PriceCatalogue> {
  pending ??= fetchCatalogue(now).catch(() => fallbackCatalogue(now));
  return pending;
}

async function fetchCatalogue(now: Date): Promise<PriceCatalogue> {
  const response = await fetch(href('/data/model-pricing.json'), {
    headers: { accept: 'application/json' },
    credentials: 'omit',
  });
  if (!response.ok) throw new Error(`Price table returned ${response.status}`);

  const raw = (await response.json()) as RawCatalogue;
  if (!Array.isArray(raw.models)) throw new Error('Price table is malformed');

  const fromRaw = (m: RawModel, curated = false, name = m.i, note?: string): PricedModel => ({
    id: m.i,
    name,
    provider: m.p,
    mode: toMode(m.m),
    context: m.ci,
    maxOutput: m.co,
    input: m.in,
    output: m.out,
    cacheRead: m.cr,
    cacheWrite: m.cw,
    deprecation: m.d,
    caps: unpackCaps(m.f, raw.flags),
    curated,
    note,
  });

  const catalogueById = new Map(raw.models.map((m) => [m.i, m]));

  /*
   * A curated entry keeps its display name, its note and its pinned position,
   * but the *numbers* come from the catalogue where the catalogue has them.
   * The hand-maintained table cannot carry cache rates or capability flags for
   * every model, and a pinned row missing its cache-read price would quietly
   * break the cache projection for exactly the four models most people use.
   */
  const curated = curatedModels(now).map((model) => {
    const twin = catalogueById.get(model.id);
    return twin ? fromRaw(twin, true, model.name, model.note) : model;
  });
  const curatedIds = new Set(curated.map((m) => m.id));

  const fromCatalogue = raw.models.filter((m) => !curatedIds.has(m.i)).map((m) => fromRaw(m));

  return {
    models: [...curated, ...fromCatalogue],
    providers: ['anthropic', ...raw.providers.filter((p) => p !== 'anthropic')],
    fetched: raw.fetched,
    source: raw.source,
    complete: true,
  };
}

/** Filters applied to the catalogue by the model picker. */
export interface ModelFilter {
  /** Free-text match against id and provider. Space-separated terms all match. */
  readonly query?: string;
  readonly provider?: string;
  readonly mode?: ModelMode;
  /** Capabilities the model must support. */
  readonly caps?: readonly CapabilityName[];
  /** Hide models whose deprecation date has passed. */
  readonly hideRetired?: boolean;
}

/**
 * Apply `filter` to `models`.
 *
 * Curated entries sort first, then by ascending input price — cheapest-first is
 * the ordering a cost tool is actually asked for.
 */
export function filterModels(
  models: readonly PricedModel[],
  filter: ModelFilter,
  now: Date = new Date(),
): PricedModel[] {
  const terms = (filter.query ?? '')
    .toLowerCase()
    .split(/\s+/)
    .filter((t) => t.length > 0);

  const today = now.toISOString().slice(0, 10);

  const matched = models.filter((model) => {
    if (filter.provider && model.provider !== filter.provider) return false;
    if (filter.mode && model.mode !== filter.mode) return false;
    if (filter.hideRetired && model.deprecation && model.deprecation < today) return false;
    if (filter.caps?.some((cap) => !model.caps[cap])) return false;
    if (terms.length > 0) {
      const haystack = `${model.id} ${model.provider} ${model.name}`.toLowerCase();
      if (!terms.every((term) => haystack.includes(term))) return false;
    }
    return true;
  });

  return matched.sort((a, b) => {
    if (a.curated !== b.curated) return a.curated ? -1 : 1;
    if (a.input !== b.input) return a.input - b.input;
    return a.id.localeCompare(b.id);
  });
}

/** Compact context-window label: `200K`, `1M`, `–` when unpublished. */
export function formatContext(tokens: number | undefined): string {
  if (!tokens) return '–';
  if (tokens >= 1_000_000) {
    // 1,048,576 is 1M as far as anyone budgeting is concerned — round, then
    // drop a trailing ".0" so it does not read as suspicious precision.
    return `${Number((tokens / 1_000_000).toFixed(1))}M`;
  }
  if (tokens >= 1_000) return `${Math.round(tokens / 1_000)}K`;
  return String(tokens);
}

/** Price per million, at a precision that keeps sub-cent rates visible. */
export function formatRate(usdPerMillion: number): string {
  if (usdPerMillion === 0) return '–';
  if (usdPerMillion < 0.01) return `$${usdPerMillion.toFixed(4)}`;
  if (usdPerMillion < 1) return `$${usdPerMillion.toFixed(3)}`;
  return `$${usdPerMillion.toFixed(2)}`;
}

/** Human label for a provider slug, e.g. `bedrock_converse` → `Bedrock converse`. */
export function providerLabel(slug: string): string {
  const spaced = slug.replace(/[_-]/g, ' ').replace(/\bai\b/gi, 'AI');
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

/** Capability flags in display order, with the short labels the UI shows. */
export const CAPABILITY_LABELS: ReadonlyArray<readonly [CapabilityName, string]> = [
  ['tools', 'Tools'],
  ['vision', 'Vision'],
  ['reasoning', 'Reasoning'],
  ['caching', 'Caching'],
  ['schema', 'JSON schema'],
  ['pdf', 'PDF'],
  ['audio', 'Audio'],
  ['websearch', 'Web search'],
  ['computer', 'Computer use'],
] as const;
