import { useEffect, useMemo, useState } from 'react';
import {
  CAPABILITY_LABELS,
  DEFAULT_SELECTION,
  fallbackCatalogue,
  filterModels,
  formatContext,
  formatRate,
  loadCatalogue,
  providerLabel,
  type CapabilityName,
  type ModelMode,
  type PriceCatalogue,
  type PricedModel,
} from '../../lib/model-pricing';
import { costOf, estimateTokens, formatUsd } from '../../lib/tokens';
import { Badge, Button, num, Panel, PasteButton, Segmented, Slider, StatRow, TextArea } from './ui';

/**
 * TokenCounter — paste text, size it, and price it against any hosted model.
 *
 * ## What changed and why
 *
 * The first version quoted four hardcoded Anthropic models. That answers "what
 * will this prompt cost me" only if the answer was already known. The catalogue
 * now comes from LiteLLM's published price list — ~2,400 token-priced models
 * across 80-odd providers — loaded from a same-origin snapshot generated by
 * `scripts/fetch-model-pricing.mjs`.
 *
 * The privacy property is unchanged and load-bearing: the *text* never leaves
 * the tab. The only request this page makes is for a static price table, and it
 * carries nothing but its own URL.
 *
 * The token count is an estimate — see `src/lib/tokens.ts` for why that is
 * unavoidable client-side, and the note in the UI that says so plainly.
 */

const SAMPLES: ReadonlyArray<{ label: string; text: string }> = [
  {
    label: 'Prose',
    text: 'Retrieval quality is decided long before the model sees a prompt. Chunking strategy, embedding choice, and the reranker do most of the work; the generation step mostly reveals whether the earlier decisions were sound.',
  },
  {
    label: 'Code',
    text: 'export async function retrieve(query: string, k = 8): Promise<Chunk[]> {\n  const embedding = await embed(query);\n  const candidates = await index.search(embedding, k * 4);\n  return rerank(query, candidates).slice(0, k);\n}',
  },
  {
    label: 'JSON schema',
    text: '{\n  "type": "object",\n  "properties": {\n    "severity": { "type": "string", "enum": ["low", "medium", "high"] },\n    "line": { "type": "integer" }\n  },\n  "required": ["severity", "line"],\n  "additionalProperties": false\n}',
  },
];

/** Number of times the input is expected to be sent, for cost projection. */
const CALL_PRESETS = [1, 100, 10_000, 1_000_000] as const;

/**
 * How many search results to render.
 *
 * The catalogue has thousands of rows and the picker is a scroll list, not a
 * data grid. Capping keeps a broad query from laying out 2,400 nodes; the count
 * of what was hidden is shown rather than silently dropped.
 */
const RESULT_LIMIT = 80;

const MODE_OPTIONS = [
  { value: 'all' as const, label: 'All' },
  { value: 'chat' as const, label: 'Chat' },
  { value: 'responses' as const, label: 'Responses' },
  { value: 'embedding' as const, label: 'Embedding' },
];

export default function TokenCounter(): React.ReactElement {
  const [text, setText] = useState<string>('');
  const [calls, setCalls] = useState<number>(1);
  /** Expected output length, as a multiple of input — drives output cost. */
  const [outputRatio, setOutputRatio] = useState<number>(0.25);
  /** Share of input tokens served from prompt cache, where the model supports it. */
  const [cacheHit, setCacheHit] = useState<number>(0);

  const [catalogue, setCatalogue] = useState<PriceCatalogue>(() => fallbackCatalogue());
  const [loading, setLoading] = useState<boolean>(true);

  const [selected, setSelected] = useState<readonly string[]>(DEFAULT_SELECTION);
  const [query, setQuery] = useState<string>('');
  const [provider, setProvider] = useState<string>('all');
  const [mode, setMode] = useState<'all' | ModelMode>('chat');
  const [caps, setCaps] = useState<readonly CapabilityName[]>([]);
  const [hideRetired, setHideRetired] = useState<boolean>(true);
  const [pickerOpen, setPickerOpen] = useState<boolean>(false);

  useEffect(() => {
    let live = true;
    void loadCatalogue().then((loaded) => {
      if (!live) return;
      setCatalogue(loaded);
      setLoading(false);
    });
    return () => {
      live = false;
    };
  }, []);

  const estimate = useMemo(() => estimateTokens(text), [text]);
  const outputTokens = Math.round(estimate.tokens * outputRatio);

  const byId = useMemo(() => new Map(catalogue.models.map((m) => [m.id, m])), [catalogue.models]);

  const results = useMemo(
    () =>
      filterModels(catalogue.models, {
        query,
        provider: provider === 'all' ? undefined : provider,
        mode: mode === 'all' ? undefined : mode,
        caps,
        hideRetired,
      }),
    [catalogue.models, query, provider, mode, caps, hideRetired],
  );

  /**
   * Cost for one model.
   *
   * Cached input is billed at the model's cache-read rate for the cached share
   * and the full rate for the rest. Models without a published cache rate are
   * priced as if nothing were cached, which is what actually happens.
   */
  const rows = useMemo(
    () =>
      selected
        .map((id) => byId.get(id))
        .filter((m): m is PricedModel => m !== undefined)
        .map((model) => {
          const cacheable = model.cacheRead !== undefined ? cacheHit : 0;
          const cachedTokens = estimate.tokens * cacheable;
          const freshTokens = estimate.tokens - cachedTokens;

          const inputCost =
            costOf(freshTokens, model.input) + costOf(cachedTokens, model.cacheRead ?? model.input);
          const outputCost = costOf(outputTokens, model.output);
          return {
            model,
            total: (inputCost + outputCost) * calls,
            fill: model.context ? estimate.tokens / model.context : 0,
            overflow: model.context !== undefined && estimate.tokens > model.context,
          };
        })
        .sort((a, b) => a.total - b.total),
    [selected, byId, estimate.tokens, outputTokens, calls, cacheHit],
  );

  const stats = [
    { label: 'tokens', value: num(estimate.tokens), hint: `±${num(estimate.margin)}` },
    { label: 'characters', value: num(estimate.characters) },
    { label: 'words', value: num(estimate.words) },
    { label: 'lines', value: num(estimate.lines) },
  ];

  const toggle = (id: string): void =>
    setSelected((prev) => (prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]));

  const toggleCap = (cap: CapabilityName): void =>
    setCaps((prev) => (prev.includes(cap) ? prev.filter((c) => c !== cap) : [...prev, cap]));

  return (
    <div className="space-y-6">
      {/* ── Input ─────────────────────────────────────────────────────── */}
      <Panel
        title="Input text"
        cornerTicks
        aside={
          <div className="flex flex-wrap items-center gap-1.5">
            <PasteButton onPaste={setText} />
            <div className="flex items-center gap-1 border-l border-[var(--c-line)] pl-2">
              {SAMPLES.map((s) => (
                <Button key={s.label} variant="quiet" onClick={() => setText(s.text)}>
                  {s.label}
                </Button>
              ))}
            </div>
            <Button variant="quiet" onClick={() => setText('')} disabled={text.length === 0}>
              Clear
            </Button>
          </div>
        }
      >
        <TextArea
          id="tc-input"
          value={text}
          onChange={setText}
          rows={9}
          placeholder="Paste a prompt, a document, or a schema. Drop a text file here. Nothing you type leaves this tab."
        />
        <StatRow stats={stats} />
      </Panel>

      <p className="text-xs leading-relaxed text-[var(--c-text-faint)]">
        <span className="text-[var(--c-warn)]">Estimate, not an exact count.</span> No production
        tokenizer runs client-side, so this uses a segment-weighted character model, typically
        within ±10% on prose and ±15% on code. For an authoritative figure, call the provider's own
        counter, e.g.{' '}
        <code className="font-mono text-[var(--c-accent)]">/v1/messages/count_tokens</code>.
      </p>

      {/* ── Projection controls ───────────────────────────────────────── */}
      <Panel title="Projection">
        <div className="grid gap-6 p-4 sm:grid-cols-3">
          <div>
            <span className="eyebrow mb-2 block">Calls</span>
            <Segmented
              label="Number of calls"
              value={String(calls)}
              options={CALL_PRESETS.map((n) => ({
                value: String(n),
                label: n >= 1_000_000 ? '1M' : n >= 1_000 ? `${n / 1_000}K` : String(n),
              }))}
              onChange={(v) => setCalls(Number(v))}
            />
          </div>

          <Slider
            id="tc-ratio"
            label="Output / input"
            value={Math.round(outputRatio * 100)}
            min={0}
            max={400}
            step={5}
            suffix={`% · ${num(outputTokens)} tok`}
            onChange={(v) => setOutputRatio(v / 100)}
          />

          <Slider
            id="tc-cache"
            label="Input from cache"
            value={Math.round(cacheHit * 100)}
            min={0}
            max={100}
            step={5}
            suffix="%"
            onChange={(v) => setCacheHit(v / 100)}
          />
        </div>
      </Panel>

      {/* ── Comparison table ──────────────────────────────────────────── */}
      <Panel
        title={`Cost · ${selected.length} model${selected.length === 1 ? '' : 's'}`}
        aside={
          <div className="flex items-center gap-2">
            {loading ? (
              <Badge tone="busy">loading prices</Badge>
            ) : catalogue.complete ? (
              <span className="font-mono text-[10px] text-[var(--c-text-faint)]">
                {num(catalogue.models.length)} models · {catalogue.fetched}
              </span>
            ) : (
              <Badge tone="warn">offline table</Badge>
            )}
            <Button
              variant={pickerOpen ? 'primary' : 'ghost'}
              onClick={() => setPickerOpen((o) => !o)}
            >
              {pickerOpen ? 'Done' : 'Add models'}
            </Button>
          </div>
        }
      >
        {pickerOpen && (
          <ModelPicker
            catalogue={catalogue}
            results={results}
            selected={selected}
            onToggle={toggle}
            query={query}
            onQuery={setQuery}
            provider={provider}
            onProvider={setProvider}
            mode={mode}
            onMode={setMode}
            caps={caps}
            onToggleCap={toggleCap}
            hideRetired={hideRetired}
            onHideRetired={setHideRetired}
          />
        )}

        {rows.length === 0 ? (
          <p className="px-4 py-8 text-center text-sm text-[var(--c-text-faint)]">
            No models selected. Use <span className="text-[var(--c-accent)]">Add models</span> to
            pick from the catalogue.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[42rem] text-sm">
              <thead>
                <tr className="border-b border-[var(--c-line)] text-left">
                  <th className="eyebrow px-4 py-2.5">Model</th>
                  <th className="eyebrow px-3 py-2.5 text-right">$/1M in</th>
                  <th className="eyebrow px-3 py-2.5 text-right">$/1M out</th>
                  <th className="eyebrow px-3 py-2.5 text-right">Cache read</th>
                  <th className="eyebrow px-3 py-2.5 text-right">Context</th>
                  <th className="eyebrow px-4 py-2.5 text-right">Est. cost</th>
                  <th className="px-2 py-2.5" />
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--c-line)]">
                {rows.map(({ model, total, fill, overflow }) => (
                  <tr key={model.id} className="hover:bg-[var(--c-raised)]">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-[12.5px] break-all">{model.name}</span>
                        {model.curated && (
                          <span className="bg-[var(--c-accent-fill)] px-1 font-mono text-[9px] text-[var(--c-accent-on-fill)]">
                            pinned
                          </span>
                        )}
                      </div>
                      <div className="mt-0.5 text-[11px] text-[var(--c-text-faint)]">
                        {model.note ?? providerLabel(model.provider)}
                        {model.deprecation && (
                          <span className="text-[var(--c-warn)]">
                            {' '}
                            · retires {model.deprecation}
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="tabular px-3 py-3 text-right font-mono text-xs">
                      {formatRate(model.input)}
                    </td>
                    <td className="tabular px-3 py-3 text-right font-mono text-xs">
                      {formatRate(model.output)}
                    </td>
                    <td className="tabular px-3 py-3 text-right font-mono text-xs text-[var(--c-text-muted)]">
                      {model.cacheRead !== undefined ? formatRate(model.cacheRead) : '—'}
                    </td>
                    <td className="px-3 py-3 text-right">
                      <div
                        className="tabular font-mono text-xs"
                        style={overflow ? { color: 'var(--c-alert)' } : undefined}
                      >
                        {formatContext(model.context)}
                      </div>
                      <div className="mt-1 ml-auto h-1 w-14 overflow-hidden rounded-full bg-[var(--c-sunken)]">
                        <div
                          className="h-full rounded-full"
                          style={{
                            width: `${Math.min(100, fill * 100)}%`,
                            background: overflow ? 'var(--c-alert)' : 'var(--c-accent-fill)',
                          }}
                        />
                      </div>
                    </td>
                    <td className="tabular px-4 py-3 text-right font-mono text-[13px] text-[var(--c-accent)]">
                      {formatUsd(total)}
                    </td>
                    <td className="px-2 py-3 text-right">
                      <Button variant="quiet" title="Remove" onClick={() => toggle(model.id)}>
                        ×
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>

      <p className="text-[11px] leading-relaxed text-[var(--c-text-faint)]">
        Rates come from{' '}
        <a
          href="https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[var(--c-accent)] underline underline-offset-2"
        >
          LiteLLM's price list
        </a>
        {catalogue.complete && `, snapshot ${catalogue.fetched}`}. They are list prices: they
        exclude batch discounts, committed-use rates, priority tiers, and per-request surcharges
        such as web search. Cache-write cost is not modelled. A first pass over a cached prefix
        bills above the input rate, so a cold run costs more than shown here.
      </p>
    </div>
  );
}

/* ── Picker ───────────────────────────────────────────────────────────── */

interface PickerProps {
  catalogue: PriceCatalogue;
  results: readonly PricedModel[];
  selected: readonly string[];
  onToggle: (id: string) => void;
  query: string;
  onQuery: (value: string) => void;
  provider: string;
  onProvider: (value: string) => void;
  mode: 'all' | ModelMode;
  onMode: (value: 'all' | ModelMode) => void;
  caps: readonly CapabilityName[];
  onToggleCap: (cap: CapabilityName) => void;
  hideRetired: boolean;
  onHideRetired: (value: boolean) => void;
}

/**
 * Catalogue browser.
 *
 * Filters are stacked rather than nested in a modal: the whole point is to see
 * the price column change as the filter narrows, which a dialog would hide.
 */
function ModelPicker(props: PickerProps): React.ReactElement {
  const shown = props.results.slice(0, RESULT_LIMIT);
  const hidden = props.results.length - shown.length;

  return (
    <div className="space-y-3 border-b border-[var(--c-line)] bg-[var(--c-raised)] p-4">
      <div className="flex flex-wrap items-center gap-2">
        <input
          type="search"
          value={props.query}
          onChange={(e) => props.onQuery(e.target.value)}
          placeholder="Search 2,400 models. Try “opus”, “gemini flash”, “nova”"
          className="min-w-[16rem] flex-1 rounded-sm border border-[var(--c-line)] bg-[var(--c-surface)] px-3 py-1.5 font-mono text-xs text-[var(--c-text)] placeholder:text-[var(--c-text-faint)] focus:border-[var(--c-accent)] focus:outline-none"
        />

        <select
          value={props.provider}
          onChange={(e) => props.onProvider(e.target.value)}
          aria-label="Provider"
          className="rounded-sm border border-[var(--c-line)] bg-[var(--c-surface)] px-2 py-1.5 font-mono text-xs text-[var(--c-text)] focus:border-[var(--c-accent)] focus:outline-none"
        >
          <option value="all">All providers</option>
          {props.catalogue.providers.map((p) => (
            <option key={p} value={p}>
              {providerLabel(p)}
            </option>
          ))}
        </select>

        <Segmented
          label="Mode"
          value={props.mode}
          options={MODE_OPTIONS}
          onChange={(v) => props.onMode(v)}
        />
      </div>

      <div className="flex flex-wrap items-center gap-1.5">
        <span className="eyebrow mr-1">Must support</span>
        {CAPABILITY_LABELS.map(([cap, label]) => {
          const active = props.caps.includes(cap);
          return (
            <button
              key={cap}
              type="button"
              aria-pressed={active}
              onClick={() => props.onToggleCap(cap)}
              className={`rounded-sm border px-1.5 py-0.5 font-mono text-[10px] transition-colors ${
                active
                  ? 'border-[var(--c-accent)] bg-[var(--c-accent-soft)] text-[var(--c-accent)]'
                  : 'border-[var(--c-line)] text-[var(--c-text-muted)] hover:text-[var(--c-text)]'
              }`}
            >
              {label}
            </button>
          );
        })}
        <label className="ml-2 flex cursor-pointer items-center gap-1.5 font-mono text-[10px] text-[var(--c-text-muted)]">
          <input
            type="checkbox"
            checked={props.hideRetired}
            onChange={(e) => props.onHideRetired(e.target.checked)}
            className="accent-[var(--c-accent)]"
          />
          Hide retired
        </label>
      </div>

      <ul className="max-h-72 divide-y divide-[var(--c-line)] overflow-y-auto rounded-sm border border-[var(--c-line)] bg-[var(--c-surface)]">
        {shown.map((model) => {
          const active = props.selected.includes(model.id);
          return (
            <li key={model.id}>
              <button
                type="button"
                onClick={() => props.onToggle(model.id)}
                aria-pressed={active}
                className={`flex w-full items-center gap-3 px-3 py-2 text-left transition-colors hover:bg-[var(--c-raised)] ${
                  active ? 'bg-[var(--c-accent-soft)]' : ''
                }`}
              >
                <span
                  aria-hidden="true"
                  className={`size-3 shrink-0 border ${
                    active
                      ? 'border-[var(--c-accent)] bg-[var(--c-accent-fill)]'
                      : 'border-[var(--c-line-strong)]'
                  }`}
                />
                <span className="min-w-0 flex-1">
                  <span className="block truncate font-mono text-[12px]">{model.name}</span>
                  <span className="block truncate text-[10px] text-[var(--c-text-faint)]">
                    {providerLabel(model.provider)} · {model.mode} · {formatContext(model.context)}{' '}
                    ctx
                  </span>
                </span>
                <span className="tabular shrink-0 font-mono text-[11px] text-[var(--c-text-muted)]">
                  {formatRate(model.input)} / {formatRate(model.output)}
                </span>
              </button>
            </li>
          );
        })}

        {props.results.length === 0 && (
          <li className="px-3 py-6 text-center text-xs text-[var(--c-text-faint)]">
            Nothing matches those filters.
          </li>
        )}
      </ul>

      <p className="font-mono text-[10px] text-[var(--c-text-faint)]">
        {num(props.results.length)} match{props.results.length === 1 ? '' : 'es'}
        {hidden > 0 &&
          ` · showing first ${RESULT_LIMIT}, narrow the search to see the other ${num(hidden)}`}
      </p>
    </div>
  );
}
